language: node_js
node_js:
  - 10
deploy:
  provider: heroku
  api_key:
    secure: Evb6mK31hLkYYBQb9wP9aPHcuR31e9hOV/qgkEVZN0mDSoXxPFxEjj9EB1xFrmYVUl+voHKGp/z2oNdycKdh/KMUPNu4eYNFXtgNd+sAo5kzxVrRVA0F0I6ulxALnHiTXK5Stm1aX8anse25N3qmhbn+KXil0J8c3yLHl1QYuGD+71P5th+0P2mgwFc+eebpA8qMKj1g5GHsqwEWK0ZSBLSn/GI02Obs2T39o6zU/R/JTHQkDmCmOwtRft1P4YEvU4QVGjNbOrjYavlmW2VT0xI4pyjRobiFVfY/EnZWJHTerWFEK6OnlNcyojCMMcZLh7NF80elXqV48KQ8Sza1O4gmGoOiNti6fsRgWgknfzNtdPYG7//xB8GKAOZV4QqYw23ES3qkoLTarOXUiH/yUQnAGKvHLqCdof4yUSpwe5cl4sK9lQTlOBb+k7Gm81c+r+F7nOxy/KdTFJx6zO+d4iCztBX2nQtM7BfzYVLQ3IRzjwM2xOLbZGInJ0tqyKHVBRIAtwyTDvNusbLCA+Ahy2cf8GaXjY70DS5rqTbDZhlGn39OLIyWlkpZ/psEvv4tQaYjrBtl/TjdbELze/zZoO27MfVTCnTj1K0SOe+VXIWpmvoL8yHRCQ02KnmG3APL1l0qZfDctzw11VObS3HM5YtHwHT+gziUGM776al+lSg=
  app: advisor-ui-ie
  on:
    branch: feature/github-actions
